FROM python:3.8-slim

# Install MLflow
RUN pip install mlflow==1.21.0

# Expose MLflow ports
EXPOSE 5000

# Set the entrypoint
ENTRYPOINT ["mlflow", "models", "serve", "-p", "5000", "-h", "0.0.0.0", "--no-conda"]
